services:
  - type: web
    name: ncm-api
    runtime: python
    rootDir: ML_Model
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn ncm_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
